gyms = {
	"Jeffrey Fuerst (Cheatham)": 13,
	"Wright House": 7,
	"Terrace View Pool": 28,
	"Tried Stone Church": 21,
	"Newman Library": 11,
	"Bburg Water Tower": 22,
	"Black House (Downtown)": 64,
	"Carnival of Mind (Downtown)": 63,
	"Something for Everyone (Downtown)": 62,
	"Nature Mural (Downtown)": 61,
	"Love Mural (Downtown)": 60,
	"VPI Moss Center": 59,
	"First Baptist (Downtown)": 58,
	"Church of Christ (Downtown)": 57,
	"Childrens Museum (S Main)": 56,
	"Church of God (S Main)": 55,
	"Mondrian Hokie (S Main)": 54,
	"VCOM (CRC)": 53,
	"Amphitheater (CRC)": 52,
	"Moss (CRC)": 51,
	"Pallets (CRC)": 50,
	"Hokie Scientist (CRC)": 49,
	"Grace Reynolds (Huckleberry)": 48,
	"University Storage": 47,
	"Bburg Pentecostal Holiness": 46,
	"Stadium Wood (Southgate)": 45,
	"German Club (Southgate)": 44,
	"Southgate Meadow": 43,
	"Virginia Tech (Southgate)": 42,
	"Lavery Plaque": 41,
	"Sheep Center": 40,
	"Dog Park": 39,
	"Blacksburg UU Church": 38,
	"Russell Fountain (VT Inn)": 35,
	"Signature Gateway (VT Inn)": 34,
	"Vet School (Prices Fork)": 33,
	"Firehouse Subs (UCB)": 32,
	"Volume Two Bookstore (UCB)": 31,
	"Antique Car (UCB Macado)": 30,
	"Grant Wood (UCB Gas)": 29,
	"Northside Presbyterian Church": 27,
	"Harvest Baptist Church": 26,
	"First Wesleyan Church": 23,
	"Pirate Sales Up (Southgate)": 18,
	"Lane Stadium": 17,
	"McComas": 15,
	"Cassell Hokie Bird": 14,
	"VT Fountain (Squires)": 12,
	"Payne Hall": 10,
	"Caldwell": 9,
	"Cadet Training Field": 8,
	"McBryde": 6,
	"Pamplin": 4,
	"Nick Brantley (Turner)": 3,
	"Burruss": 2,
	"Tau Beta Pi": 1,
	# from here down are ex
	"Bburg Aquatic Center": 24,
	"Net Spire (Bennett Park)": 37,
	"Moist Cove (Nellies Cave)": 36,
	"Hahn (Caboose Park)": 25,
	"Tot Lot (Golf Course)": 20,
	"Town Bicentennial": 19,
	"Maid in Mud (Hahn Garden)": 16,
	"Duckpond Gazebo": 5,
}
hardcodes = {
	  "furest": "fuerst"
	, "fountain": "vt fountian"
	, "first baptist church of blacksburg": "first baptist"
	, "first baptist church of bburg": "first baptist"
}
